name: 'Bump Nuget Version'
description: 'This action will add a Nuget source'
inputs:
  level:
    description: 'Version level (patch, minor or major)'     
    required: true
    default: 'patch'
  route:
    description: 'package.json route'     
    required: false
    default: ''
    
runs:
  using: 'composite'
  steps: 
    - run: sudo npm install -g semver
      shell: bash
    - run: export level=${{ inputs.level }}; route=${{ inputs.route }}; ${{ github.action_path }}/bump.sh
      shell: bash
