name: Npm - Build, Bump and Push (GitHub Registry)

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The version of Node.js to use'
        required: false
        default: '14'
        type: 'string'
    secrets:
      github-token:
        description: 'The GitHub PAT token to perform checkout and publish.'
        required: true

jobs:
  dpdm:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_AUTH_TOKEN: ${{ secrets.github-token }}

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v6

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@unosquare'
          cache: 'npm'

      - name: 🤠 npm install
        run: npm ci

      - name: 💅 Prettier
        run: npm run prettier

      - name: ⭕ Circular ref check
        run: npm run dpdm

      - name: 🎠 Test
        run: npm test

      - name: 🏗 Build
        run: npm run build
